# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3b4112ce4b86dd5b07a91c10d2272b2072657c17d448309b46e4f0cc165d8bbc1a681db27197112633ef6da76d8d873d081cb84b650d0e161fd38fe57b2605d

test:
  secret_key_base: 955c8c2a1695904a0c2d484cc69ed297e6a558be2ff875f80d220f627cd467c6a2169cb841ed37892ac136829ed3405138ec66fc4b5f831ecb4e0ff69a917447

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
